name: CI Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 8.x]
    
    steps:
    - uses: actions/checkout@v1
    - uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ahmdichsan-profile
        heroku_email: ahmdichsanb@gmail.com

    - name: npm install
      run: |
        npm install
    - name: npm test
      run: |
        npm test 
      env:
        CI: true
      
    - name: npm run build
      run: |
        npm run build

    # - name: Add remote origin
    #   run: |
    #     git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    # - name: Deploy to Heroku
    #   run: |
    #     git push heroku HEAD:master -f

